// <auto-generated />
using System;
using Api_Pcto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_Pcto.Migrations.MyDb
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220219093833_CamMig")]
    partial class CamMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Api_Pcto.Telecamera_Data", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data_creazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("num_like")
                        .HasColumnType("INTEGER");

                    b.Property<int>("num_salvati")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("eletelecamere");
                });
#pragma warning restore 612, 618
        }
    }
}
